Fr iscsi map
FeixiDev/Orion pull request #23
Opened 2020-10-20 08:05 UTC by Zaneczy

1.按照建议修改LUN ID获取机制改成设备名/dev/drbd之后的数字减去1000；
2.添加map创建之后启动resource，并通过crm st检查状态情况，（由于状态可能有延迟，设置为每秒检查一次，检查成功直接反馈，检查5次后还是失败才反馈失败）将状态情况打印反馈给用户；

2020-10-21 07:08 UTC, Zaneczy commented
A. map删除前，通过crm config获取resource状态，改为通过crm st获取resource状态，重复获取直到状态为stop，最多重复获取5次；
B. 修改优化map创建时的所有提示信息，map删除时的所有提示信息；
C. 按照建议优化map创建部分的代码，分层；

2020-10-21 09:37 UTC, Zaneczy commented on VersaTEL_G2_CLI/execute/crm.py
> +                s.prt_log(f"delete resource fail", 1)
这个是删除成功就会打印resource删除成功，如果这个resource有对应的colocation跟order，会一起删除，这时就还会打印colocation，order删除成功。

2020-10-21 09:54 UTC, mattie-feng requested changes

2020-10-21 09:54 UTC, mattie-feng commented on VersaTEL_G2_CLI/execute/iscsi.py
> +                    return True
* obj_crm.checkout_status_start(res)要加if吧，确认为Started再写入配置文件
* 一组DiskGroup有三个disk，其中两个disk map创建成功，一个失败，这个map应该不算成功，不写入配置文件
* return True不应该在这里

2020-10-22 05:54 UTC, Zaneczy commented on VersaTEL_G2_CLI/execute/iscsi.py
> +                    return True
- obj_crm.checkout_status_start(res)要加if吧，确认为Started再写入配置文件
这个我跟Frederic，Klay确认过才写的，需求是无论started还是stopped都算map成功

- 一组DiskGroup有三个disk，其中两个disk map创建成功，一个失败，这个map应该不算成功，不写入配置文件
这个还需详细讨论需求情况，Frederic跟Klay跟你说的不一样。。。

- return True不应该在这里
的确是，是我昨天改代码时改错了，已修复

2020-10-26 01:14 UTC, Zaneczy commented on VersaTEL_G2_CLI/execute/iscsi.py
> +                    return True
已经修改代码：一组DiskGroup有三个disk，需要创建resource跟配置时，其中有一个disk创建失败，则会提示用户map失败打印失败的原因，并回退删除刚创建成功的其他disk的resource；

2020-10-28 08:08 UTC, userhei commented on VersaTEL_G2_CLI/execute/crm.py
> +                s.prt_log(f"delete resource fail", 1)
if result['sts']:
            s.prt_log(f"delete resource success: {res}", 0)
        if result:

这个操作仍然很奇怪，

2020-10-28 08:47 UTC, Zaneczy commented on VersaTEL_G2_CLI/execute/crm.py
> +                s.prt_log(f"delete resource fail", 1)
操作是没问题的，看着奇怪也可以放里面，已修改

2020-10-28 12:26 UTC, userhei reviewed
找时间沟通一下 crm.py Comment on lines +185 to +196 逻辑

2020-10-29 07:50 UTC, merged